<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('carts',function(Blueprint $t){$t->increments('cart_id');$t->unsignedInteger('user_id')->unique();$t->timestamps();$t->foreign('user_id')->references('user_id')->on('users')->cascadeOnDelete();});
Schema::create('cart_items',function(Blueprint $t){$t->increments('cart_item_id');$t->unsignedInteger('cart_id');$t->unsignedInteger('product_id');$t->unsignedInteger('quantity');$t->timestamps();$t->foreign('cart_id')->references('cart_id')->on('carts')->cascadeOnDelete();$t->foreign('product_id')->references('product_id')->on('products')->cascadeOnDelete();$t->unique(['cart_id','product_id']);});DB::statement('ALTER TABLE cart_items ADD CONSTRAINT cart_items_quantity_positive CHECK (quantity > 0)');
Schema::create('orders',function(Blueprint $t){$t->increments('order_id');$t->unsignedInteger('user_id');$t->string('status',20)->default('pending');$t->decimal('total_amount',14,2)->default(0);$t->jsonb('shipping_address');$t->text('note')->nullable();$t->timestamps();$t->foreign('user_id')->references('user_id')->on('users')->restrictOnDelete();});DB::statement("ALTER TABLE orders ADD CONSTRAINT orders_status_check CHECK (status IN ('pending','confirmed','processing','shipping','completed','cancelled'))");DB::statement('ALTER TABLE orders ADD CONSTRAINT orders_total_nonnegative CHECK (total_amount >= 0)');
Schema::create('order_items',function(Blueprint $t){$t->increments('order_item_id');$t->unsignedInteger('order_id');$t->unsignedInteger('product_id');$t->string('product_name');$t->unsignedInteger('quantity');$t->decimal('price',14,2);$t->timestamps();$t->foreign('order_id')->references('order_id')->on('orders')->cascadeOnDelete();$t->foreign('product_id')->references('product_id')->on('products')->restrictOnDelete();});DB::statement('ALTER TABLE order_items ADD CONSTRAINT order_items_price_nonnegative CHECK (price >= 0)');DB::statement('ALTER TABLE order_items ADD CONSTRAINT order_items_quantity_positive CHECK (quantity > 0)');
Schema::create('payments',function(Blueprint $t){$t->increments('payment_id');$t->unsignedInteger('order_id')->unique();$t->string('method',40);$t->string('status',20)->default('pending');$t->decimal('amount',14,2);$t->string('transaction_code',190)->nullable();$t->jsonb('gateway_payload')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();$t->foreign('order_id')->references('order_id')->on('orders')->cascadeOnDelete();});DB::statement("ALTER TABLE payments ADD CONSTRAINT payments_status_check CHECK (status IN ('pending','success','failed'))");DB::statement('ALTER TABLE payments ADD CONSTRAINT payments_amount_nonnegative CHECK (amount >= 0)');
}public function down():void{Schema::dropIfExists('payments');Schema::dropIfExists('order_items');Schema::dropIfExists('orders');Schema::dropIfExists('cart_items');Schema::dropIfExists('carts');}};
