<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('categories',function(Blueprint $t){$t->increments('category_id');$t->string('name',190);$t->string('slug',190)->unique();$t->text('description')->nullable();$t->unsignedInteger('parent_id')->nullable();$t->boolean('is_active')->default(true);$t->unsignedInteger('position')->default(0);$t->timestamps();$t->foreign('parent_id')->references('category_id')->on('categories')->nullOnDelete();});
Schema::create('products',function(Blueprint $t){$t->increments('product_id');$t->unsignedInteger('category_id');$t->unsignedInteger('media_id')->nullable();$t->string('name');$t->string('slug')->unique();$t->string('sku',100)->unique();$t->text('short_description')->nullable();$t->text('description')->nullable();$t->decimal('price',14,2);$t->integer('stock_quantity');$t->boolean('is_active')->default(true);$t->timestamps();$t->foreign('category_id')->references('category_id')->on('categories')->restrictOnDelete();$t->foreign('media_id')->references('media_id')->on('media')->nullOnDelete();});DB::statement('ALTER TABLE products ADD CONSTRAINT products_price_nonnegative CHECK (price >= 0)');DB::statement('ALTER TABLE products ADD CONSTRAINT products_stock_nonnegative CHECK (stock_quantity >= 0)');
Schema::create('article_categories',function(Blueprint $t){$t->increments('article_category_id');$t->string('name',190);$t->string('slug',190)->unique();$t->text('description')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('articles',function(Blueprint $t){$t->increments('article_id');$t->unsignedInteger('article_category_id');$t->unsignedInteger('thumbnail_id')->nullable();$t->string('title');$t->string('slug')->unique();$t->text('excerpt')->nullable();$t->text('content');$t->string('status',20)->default('draft');$t->timestamp('published_at')->nullable();$t->timestamps();$t->foreign('article_category_id')->references('article_category_id')->on('article_categories')->restrictOnDelete();$t->foreign('thumbnail_id')->references('media_id')->on('media')->nullOnDelete();});DB::statement("ALTER TABLE articles ADD CONSTRAINT articles_status_check CHECK (status IN ('draft','published','archived'))");
Schema::create('user_wishlists',function(Blueprint $t){$t->increments('wishlist_id');$t->unsignedInteger('user_id');$t->unsignedInteger('product_id');$t->timestamps();$t->foreign('user_id')->references('user_id')->on('users')->cascadeOnDelete();$t->foreign('product_id')->references('product_id')->on('products')->cascadeOnDelete();$t->unique(['user_id','product_id']);});
}public function down():void{Schema::dropIfExists('user_wishlists');Schema::dropIfExists('articles');Schema::dropIfExists('article_categories');Schema::dropIfExists('products');Schema::dropIfExists('categories');}};
