<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Plus, Pencil, Trash2, Image as ImageIcon } from 'lucide-vue-next'
import { api } from '@/services/api';import { errorMessage } from '@/utils/errors';import { dateTime, slugify } from '@/utils/format'
import type { Article, ArticleCategory } from '@/types/api'
import PageHeader from '@/components/PageHeader.vue';import BaseModal from '@/components/BaseModal.vue';import PaginationBar from '@/components/PaginationBar.vue';import StatusBadge from '@/components/StatusBadge.vue';import ConfirmDialog from '@/components/ConfirmDialog.vue';import EmptyState from '@/components/EmptyState.vue'
const rows=ref<Article[]>([]),cats=ref<ArticleCategory[]>([]),page=ref(1),lastPage=ref(1),total=ref(0),open=ref(false),saving=ref(false),loading=ref(false),err=ref(''),editing=ref<Article|null>(null),deleteId=ref<number|null>(null),thumb=ref<File|null>(null)
const form=reactive<any>({article_category_id:null,thumbnail_id:null,title:'',slug:'',excerpt:'',content:'',status:'draft',published_at:''})
async function load(p=page.value){loading.value=true;try{const r=await api.articles({page:p});rows.value=r.data;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}finally{loading.value=false}}
async function loadCats(){cats.value=(await api.articleCategories()).data}
function create(){editing.value=null;thumb.value=null;Object.assign(form,{article_category_id:cats.value[0]?.article_category_id||null,thumbnail_id:null,title:'',slug:'',excerpt:'',content:'',status:'draft',published_at:''});err.value='';open.value=true}
function localDate(v?:string|null){if(!v)return'';const d=new Date(v);const p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function edit(x:Article){editing.value=x;thumb.value=null;Object.assign(form,{article_category_id:x.article_category_id,thumbnail_id:x.thumbnail_id||null,title:x.title,slug:x.slug,excerpt:x.excerpt||'',content:x.content,status:x.status,published_at:localDate(x.published_at)});err.value='';open.value=true}
function autoSlug(){if(!editing.value||!form.slug)form.slug=slugify(form.title)}
function pick(e:Event){thumb.value=(e.target as HTMLInputElement).files?.[0]||null}
async function save(){saving.value=true;err.value='';try{const payload={...form,article_category_id:Number(form.article_category_id),published_at:form.published_at||null};const saved=await api.saveArticle(payload,editing.value?.article_id);if(thumb.value)await api.uploadArticleThumbnail(saved.article_id,thumb.value);open.value=false;await load()}catch(e){err.value=errorMessage(e)}finally{saving.value=false}}
async function remove(){if(!deleteId.value)return;try{await api.deleteArticle(deleteId.value);deleteId.value=null;await load()}catch(e){alert(errorMessage(e))}}
onMounted(async()=>{await Promise.all([load(),loadCats()])})
</script>
<template><PageHeader title="Bài viết CMS" description="Soạn thảo nội dung, trạng thái xuất bản và ảnh đại diện bài viết."><button class="btn btn-primary" @click="create"><Plus :size="16"/>Viết bài mới</button></PageHeader><section class="card"><div v-if="loading" class="loading-line"/><EmptyState v-if="!loading&&!rows.length" title="Chưa có bài viết"/><div v-else class="table-wrap"><table class="data-table"><thead><tr><th>Bài viết</th><th>Chuyên mục</th><th>Trạng thái</th><th>Ngày đăng</th><th></th></tr></thead><tbody><tr v-for="x in rows" :key="x.article_id"><td><div class="cell-title"><img v-if="x.thumbnail?.drive_view_url" :src="x.thumbnail.drive_view_url"/><div v-else style="width:42px;height:42px;border:1px solid var(--line);border-radius:9px;display:grid;place-items:center"><ImageIcon :size="17"/></div><div><strong>{{x.title}}</strong><small>#{{x.article_id}} · {{x.slug}}</small></div></div></td><td>{{x.category?.name||x.article_category_id}}</td><td><StatusBadge :value="x.status"/></td><td>{{dateTime(x.published_at)}}</td><td><div class="actions"><button class="btn btn-secondary btn-sm" @click="edit(x)"><Pencil :size="14"/>Sửa</button><button class="btn btn-danger btn-sm" @click="deleteId=x.article_id"><Trash2 :size="14"/></button></div></td></tr></tbody></table></div><PaginationBar v-if="rows.length" :page="page" :last-page="lastPage" :total="total" @change="load"/></section>
<BaseModal :open="open" :title="editing?'Sửa bài viết':'Tạo bài viết'" wide @close="open=false"><div v-if="err" class="alert alert-danger">{{err}}</div><div class="form-grid"><label class="field"><span>Tiêu đề *</span><input v-model="form.title" @blur="autoSlug"/></label><label class="field"><span>Slug *</span><input v-model="form.slug"/></label><label class="field"><span>Chuyên mục *</span><select v-model.number="form.article_category_id"><option v-for="c in cats" :key="c.article_category_id" :value="c.article_category_id">{{c.name}}</option></select></label><label class="field"><span>Trạng thái *</span><select v-model="form.status"><option value="draft">Bản nháp</option><option value="published">Đã đăng</option><option value="archived">Lưu trữ</option></select></label><label class="field"><span>Thời gian xuất bản</span><input v-model="form.published_at" type="datetime-local"/></label><label class="field"><span>Thumbnail</span><input type="file" accept="image/*" @change="pick"/><small>{{thumb?.name||'Để trống nếu giữ ảnh cũ'}}</small></label><label class="field full"><span>Mô tả ngắn</span><textarea v-model="form.excerpt" rows="3"/></label><label class="field full"><span>Nội dung *</span><textarea v-model="form.content" rows="14" placeholder="Có thể lưu HTML hoặc nội dung từ editor phía frontend."/></label></div><template #footer><button class="btn btn-secondary" @click="open=false">Hủy</button><button class="btn btn-primary" :disabled="saving" @click="save">{{saving?'Đang lưu...':'Lưu bài viết'}}</button></template></BaseModal><ConfirmDialog :open="!!deleteId" title="Xóa bài viết" message="Nếu bài viết đang được menu trỏ tới, PostgreSQL sẽ từ chối xóa để tránh menu bị hỏng." @cancel="deleteId=null" @confirm="remove"/></template>
