<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';import { Plus, Pencil, Trash2 } from 'lucide-vue-next';import { api } from '@/services/api';import { errorMessage } from '@/utils/errors';import { slugify } from '@/utils/format';import type { Category } from '@/types/api';import PageHeader from '@/components/PageHeader.vue';import BaseModal from '@/components/BaseModal.vue';import StatusBadge from '@/components/StatusBadge.vue';import ConfirmDialog from '@/components/ConfirmDialog.vue';
const rows=ref<Category[]>([]),loading=ref(false),open=ref(false),saving=ref(false),err=ref(''),editing=ref<Category|null>(null),deleteId=ref<number|null>(null);const form=reactive<any>({name:'',slug:'',description:'',parent_id:null,is_active:true,position:0})
async function load(){loading.value=true;try{rows.value=(await api.categories()).data}finally{loading.value=false}}
function create(){editing.value=null;Object.assign(form,{name:'',slug:'',description:'',parent_id:null,is_active:true,position:0});err.value='';open.value=true}
function edit(x:Category){editing.value=x;Object.assign(form,{name:x.name,slug:x.slug,description:x.description||'',parent_id:x.parent_id||null,is_active:x.is_active,position:x.position});err.value='';open.value=true}
function autoSlug(){if(!editing.value||!form.slug)form.slug=slugify(form.name)}
async function save(){saving.value=true;err.value='';try{await api.saveCategory({...form,parent_id:form.parent_id||null},editing.value?.category_id);open.value=false;await load()}catch(e){err.value=errorMessage(e)}finally{saving.value=false}}
async function remove(){if(!deleteId.value)return;try{await api.deleteCategory(deleteId.value);deleteId.value=null;await load()}catch(e){alert(errorMessage(e))}}
onMounted(load)
</script>
<template><PageHeader title="Danh mục sản phẩm" description="Tổ chức sản phẩm theo danh mục cha/con và thứ tự hiển thị."><button class="btn btn-primary" @click="create"><Plus :size="16"/>Thêm danh mục</button></PageHeader><section class="card"><div v-if="loading" class="loading-line"/><div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Tên danh mục</th><th>Slug</th><th>Danh mục cha</th><th>Vị trí</th><th>Trạng thái</th><th></th></tr></thead><tbody><tr v-for="x in rows" :key="x.category_id"><td>#{{x.category_id}}</td><td><strong>{{x.name}}</strong></td><td class="muted">{{x.slug}}</td><td>{{rows.find(p=>p.category_id===x.parent_id)?.name||'—'}}</td><td>{{x.position}}</td><td><StatusBadge :value="x.is_active"/></td><td><div class="actions"><button class="btn btn-secondary btn-sm" @click="edit(x)"><Pencil :size="14"/>Sửa</button><button class="btn btn-danger btn-sm" @click="deleteId=x.category_id"><Trash2 :size="14"/></button></div></td></tr></tbody></table></div></section><BaseModal :open="open" :title="editing?'Sửa danh mục':'Thêm danh mục'" @close="open=false"><div v-if="err" class="alert alert-danger">{{err}}</div><div class="form-grid"><label class="field"><span>Tên danh mục</span><input v-model="form.name" @blur="autoSlug" required/></label><label class="field"><span>Slug</span><input v-model="form.slug" required/></label><label class="field"><span>Danh mục cha</span><select v-model="form.parent_id"><option :value="null">Không có</option><option v-for="x in rows.filter(r=>r.category_id!==editing?.category_id)" :key="x.category_id" :value="x.category_id">{{x.name}}</option></select></label><label class="field"><span>Vị trí</span><input v-model.number="form.position" type="number" min="0"/></label><label class="field full"><span>Mô tả</span><textarea v-model="form.description"/></label><div class="switch-row full"><span>Đang hoạt động</span><label class="switch"><input v-model="form.is_active" type="checkbox"><i/></label></div></div><template #footer><button class="btn btn-secondary" @click="open=false">Hủy</button><button class="btn btn-primary" :disabled="saving" @click="save">{{saving?'Đang lưu...':'Lưu danh mục'}}</button></template></BaseModal><ConfirmDialog :open="!!deleteId" title="Xóa danh mục" message="Danh mục đang được sản phẩm sử dụng sẽ bị PostgreSQL từ chối xóa để bảo toàn dữ liệu." @cancel="deleteId=null" @confirm="remove"/></template>
