<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Users, Package, Newspaper, ShoppingBag, Clock3, WalletCards, Plus, PanelsTopLeft, Menu, Images } from 'lucide-vue-next'
import { api } from '@/services/api'
import { money } from '@/utils/format'
import type { DashboardStats } from '@/types/api'
import StatCard from '@/components/StatCard.vue';import PageHeader from '@/components/PageHeader.vue'
const stats=ref<DashboardStats|null>(null);const loading=ref(true)
onMounted(async()=>{try{stats.value=await api.dashboard()}finally{loading.value=false}})
</script>
<template><PageHeader title="Tổng quan" description="Tình hình vận hành nhanh của hệ thống thương mại điện tử."/><div v-if="loading" class="loading-line"/>
<div v-else-if="stats" class="stats-grid"><StatCard label="Khách hàng" :value="stats.users" :icon="Users"/><StatCard label="Sản phẩm" :value="stats.products" :icon="Package"/><StatCard label="Bài viết" :value="stats.articles" :icon="Newspaper"/><StatCard label="Tổng đơn hàng" :value="stats.orders" :icon="ShoppingBag"/><StatCard label="Đơn chờ xử lý" :value="stats.pending_orders" :icon="Clock3"/><StatCard label="Doanh thu hoàn thành" :value="money(stats.revenue_completed)" :icon="WalletCards"/></div>
<div class="dashboard-grid"><section class="card"><div class="card-header"><h3>Truy cập nhanh</h3></div><div class="card-body quick-grid"><router-link class="quick-link" to="/products"><Plus :size="19"/><div><strong>Quản lý sản phẩm</strong><small>Thêm, sửa, tồn kho và ảnh</small></div></router-link><router-link class="quick-link" to="/orders"><ShoppingBag :size="19"/><div><strong>Xử lý đơn hàng</strong><small>Xác nhận và cập nhật giao hàng</small></div></router-link><router-link class="quick-link" to="/homepage"><PanelsTopLeft :size="19"/><div><strong>Bố cục trang chủ</strong><small>Bật/tắt và sắp xếp section</small></div></router-link><router-link class="quick-link" to="/menus"><Menu :size="19"/><div><strong>Menu điều hướng</strong><small>Quản lý cây menu đa hình</small></div></router-link><router-link class="quick-link" to="/articles"><Newspaper :size="19"/><div><strong>Nội dung CMS</strong><small>Soạn và xuất bản bài viết</small></div></router-link><router-link class="quick-link" to="/media"><Images :size="19"/><div><strong>Thư viện Media</strong><small>Google Drive tập trung</small></div></router-link></div></section><section class="card"><div class="card-header"><h3>Kiến trúc hệ thống</h3></div><div class="card-body"><div class="detail-grid"><div class="detail-item"><span>Website khách</span><strong>NuxtJS · :3000</strong></div><div class="detail-item"><span>Trang quản trị</span><strong>VueJS · :5173</strong></div><div class="detail-item"><span>Public API</span><strong>/api/v1</strong></div><div class="detail-item"><span>Admin API</span><strong>/api/admin/v1</strong></div></div><p class="muted" style="font-size:12px;line-height:1.6;margin:14px 0 0">Admin là SPA độc lập, chỉ dùng API quản trị có middleware <code>auth:sanctum + admin</code>. Website người dùng không chứa mã nguồn quản trị.</p></div></section></div></template>
