<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';import { Plus, Pencil, Trash2, ArrowUp, ArrowDown } from 'lucide-vue-next';import { api } from '@/services/api';import { errorMessage } from '@/utils/errors';import type { HomepageSection } from '@/types/api';import PageHeader from '@/components/PageHeader.vue';import BaseModal from '@/components/BaseModal.vue';import StatusBadge from '@/components/StatusBadge.vue';import ConfirmDialog from '@/components/ConfirmDialog.vue';import EmptyState from '@/components/EmptyState.vue'
const rows=ref<HomepageSection[]>([]),open=ref(false),saving=ref(false),reordering=ref(false),err=ref(''),editing=ref<HomepageSection|null>(null),deleteId=ref<number|null>(null);const types=['menu_bar','main_slider','category_grid','product_carousel','article_list','custom_html'];const form=reactive<any>({title:'',type:'product_carousel',position:0,is_visible:true,settings:'{}'})
async function load(){rows.value=await api.sections()}
function create(){editing.value=null;Object.assign(form,{title:'',type:'product_carousel',position:rows.value.length,is_visible:true,settings:'{}'});err.value='';open.value=true}
function edit(x:HomepageSection){editing.value=x;Object.assign(form,{title:x.title,type:x.type,position:x.position,is_visible:x.is_visible,settings:JSON.stringify(x.settings||{},null,2)});err.value='';open.value=true}
async function save(){saving.value=true;err.value='';try{let settings={};try{settings=form.settings?JSON.parse(form.settings):{}}catch{throw new Error('Settings phải là JSON hợp lệ.')}await api.saveSection({...form,settings,position:Number(form.position)},editing.value?.section_id);open.value=false;await load()}catch(e){err.value=errorMessage(e)}finally{saving.value=false}}
async function move(index:number,delta:number){const j=index+delta;if(j<0||j>=rows.value.length)return;const copy=[...rows.value];[copy[index],copy[j]]=[copy[j],copy[index]];copy.forEach((x,i)=>x.position=i);rows.value=copy;reordering.value=true;try{await api.reorderSections(copy.map(x=>({section_id:x.section_id,position:x.position})))}catch(e){alert(errorMessage(e));await load()}finally{reordering.value=false}}
async function remove(){if(deleteId.value){try{await api.deleteSection(deleteId.value);deleteId.value=null;await load()}catch(e){alert(errorMessage(e))}}}
onMounted(load)
</script>
<template><PageHeader title="Bố cục trang chủ" description="Điều khiển các section động mà NuxtJS sẽ render theo thứ tự position."><button class="btn btn-primary" @click="create"><Plus :size="16"/>Thêm section</button></PageHeader><div v-if="reordering" class="loading-line"/><EmptyState v-if="!rows.length" title="Chưa có section trang chủ"/><div v-else class="section-list"><div class="section-row" v-for="(x,i) in rows" :key="x.section_id"><div class="section-order">{{i+1}}</div><div class="section-main"><strong>{{x.title}}</strong><small>{{x.type}} · position {{x.position}} · #{{x.section_id}}</small></div><StatusBadge :value="x.is_visible"/><div class="actions"><button class="btn btn-secondary btn-sm" :disabled="i===0" @click="move(i,-1)"><ArrowUp :size="14"/></button><button class="btn btn-secondary btn-sm" :disabled="i===rows.length-1" @click="move(i,1)"><ArrowDown :size="14"/></button><button class="btn btn-secondary btn-sm" @click="edit(x)"><Pencil :size="14"/>Sửa</button><button class="btn btn-danger btn-sm" @click="deleteId=x.section_id"><Trash2 :size="14"/></button></div></div></div>
<BaseModal :open="open" :title="editing?'Sửa section':'Thêm section'" @close="open=false"><div v-if="err" class="alert alert-danger">{{err}}</div><div class="form-grid"><label class="field"><span>Tiêu đề</span><input v-model="form.title"/></label><label class="field"><span>Loại section</span><select v-model="form.type"><option v-for="t in types" :key="t" :value="t">{{t}}</option></select></label><label class="field"><span>Vị trí</span><input v-model.number="form.position" type="number" min="0"/></label><div class="switch-row"><span>Hiển thị</span><label class="switch"><input v-model="form.is_visible" type="checkbox"><i/></label></div><label class="field full"><span>Settings JSONB</span><textarea v-model="form.settings" rows="11"/><small>Ví dụ: {"limit": 8, "category_id": 5}</small></label></div><template #footer><button class="btn btn-secondary" @click="open=false">Hủy</button><button class="btn btn-primary" :disabled="saving" @click="save">{{saving?'Đang lưu...':'Lưu section'}}</button></template></BaseModal><ConfirmDialog :open="!!deleteId" title="Xóa section" message="Section sẽ biến mất khỏi cấu hình trang chủ. Frontend NuxtJS không còn nhận section này từ API." @cancel="deleteId=null" @confirm="remove"/></template>
