<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';import { Plus, Pencil, Trash2, ChevronRight } from 'lucide-vue-next';import { api } from '@/services/api';import { errorMessage } from '@/utils/errors';import type { Article, ArticleCategory, Category, Menu, Product } from '@/types/api';import PageHeader from '@/components/PageHeader.vue';import BaseModal from '@/components/BaseModal.vue';import StatusBadge from '@/components/StatusBadge.vue';import ConfirmDialog from '@/components/ConfirmDialog.vue';import EmptyState from '@/components/EmptyState.vue'
const flat=ref<Menu[]>([]),tree=ref<Menu[]>([]),cats=ref<Category[]>([]),products=ref<Product[]>([]),articleCats=ref<ArticleCategory[]>([]),articles=ref<Article[]>([]),open=ref(false),saving=ref(false),err=ref(''),editing=ref<Menu|null>(null),deleteId=ref<number|null>(null)
const form=reactive<any>({title:'',parent_id:null,position:0,is_visible:true,target_type:'url',target_id:null,url:'/'})
const flattenedTree=computed(()=>{const out:{item:Menu;level:number}[]=[];const walk=(items:Menu[],level=0)=>items.forEach(x=>{out.push({item:x,level});if(x.children?.length)walk(x.children,level+1)});walk(tree.value);return out})
async function load(){const r=await api.menus();flat.value=r.flat;tree.value=r.tree}
async function refs(){const [c,p,ac,a]=await Promise.all([api.categories(),api.products(),api.articleCategories(),api.articles()]);cats.value=c.data;products.value=p.data;articleCats.value=ac.data;articles.value=a.data}
function targetOf(x:Menu){if(x.category_id)return ['category',x.category_id];if(x.product_id)return ['product',x.product_id];if(x.article_category_id)return ['article_category',x.article_category_id];if(x.article_id)return ['article',x.article_id];return ['url',null]}
function create(){editing.value=null;Object.assign(form,{title:'',parent_id:null,position:flat.value.length,is_visible:true,target_type:'url',target_id:null,url:'/'});err.value='';open.value=true}
function edit(x:Menu){editing.value=x;const [type,id]=targetOf(x);Object.assign(form,{title:x.title,parent_id:x.parent_id||null,position:x.position,is_visible:x.is_visible,target_type:type,target_id:id,url:x.url||'/'});err.value='';open.value=true}
function options(){if(form.target_type==='category')return cats.value.map(x=>({id:x.category_id,label:x.name}));if(form.target_type==='product')return products.value.map(x=>({id:x.product_id,label:x.name}));if(form.target_type==='article_category')return articleCats.value.map(x=>({id:x.article_category_id,label:x.name}));if(form.target_type==='article')return articles.value.map(x=>({id:x.article_id,label:x.title}));return []}
async function save(){saving.value=true;err.value='';try{const payload:any={title:form.title,parent_id:form.parent_id||null,position:Number(form.position),is_visible:form.is_visible,url:null,category_id:null,product_id:null,article_category_id:null,article_id:null};if(form.target_type==='url')payload.url=form.url;else payload[`${form.target_type}_id`]=Number(form.target_id);await api.saveMenu(payload,editing.value?.menu_id);open.value=false;await load()}catch(e){err.value=errorMessage(e)}finally{saving.value=false}}
async function remove(){if(deleteId.value){try{await api.deleteMenu(deleteId.value);deleteId.value=null;await load()}catch(e){alert(errorMessage(e))}}}
onMounted(async()=>{await Promise.all([load(),refs()])})
</script>
<template><PageHeader title="Menu điều hướng" description="Cây menu đệ quy; mỗi menu chỉ được trỏ tới đúng một thực thể hoặc Custom Link."><button class="btn btn-primary" @click="create"><Plus :size="16"/>Thêm menu</button></PageHeader><section class="card"><div class="card-body"><EmptyState v-if="!flattenedTree.length" title="Chưa có menu"/><div v-else class="menu-tree"><div class="menu-node" v-for="n in flattenedTree" :key="n.item.menu_id"><div class="menu-indent" :style="{'--level':n.level}"/><ChevronRight v-if="n.level" :size="14" class="muted"/><div class="menu-node-main"><strong>{{n.item.title}}</strong><small>#{{n.item.menu_id}} · {{n.item.resolved_url||n.item.url||'Target động'}} · position {{n.item.position}}</small></div><StatusBadge :value="n.item.is_visible"/><div class="actions"><button class="btn btn-secondary btn-sm" @click="edit(n.item)"><Pencil :size="14"/>Sửa</button><button class="btn btn-danger btn-sm" @click="deleteId=n.item.menu_id"><Trash2 :size="14"/></button></div></div></div></div></section>
<BaseModal :open="open" :title="editing?'Sửa menu':'Thêm menu'" @close="open=false"><div v-if="err" class="alert alert-danger">{{err}}</div><div class="form-grid"><label class="field"><span>Tiêu đề</span><input v-model="form.title"/></label><label class="field"><span>Menu cha</span><select v-model="form.parent_id"><option :value="null">Menu gốc</option><option v-for="x in flat.filter(m=>m.menu_id!==editing?.menu_id)" :key="x.menu_id" :value="x.menu_id">#{{x.menu_id}} {{x.title}}</option></select></label><label class="field"><span>Loại đích</span><select v-model="form.target_type" @change="form.target_id=null"><option value="url">Custom Link</option><option value="category">Danh mục sản phẩm</option><option value="product">Sản phẩm</option><option value="article_category">Chuyên mục bài viết</option><option value="article">Bài viết</option></select></label><label v-if="form.target_type!=='url'" class="field"><span>Đối tượng</span><select v-model="form.target_id"><option :value="null">Chọn...</option><option v-for="x in options()" :key="x.id" :value="x.id">#{{x.id}} {{x.label}}</option></select></label><label v-else class="field"><span>URL tự do</span><input v-model="form.url" placeholder="/gioi-thieu"/></label><label class="field"><span>Vị trí</span><input v-model.number="form.position" type="number" min="0"/></label><div class="switch-row full"><span>Hiển thị menu</span><label class="switch"><input v-model="form.is_visible" type="checkbox"><i/></label></div></div><template #footer><button class="btn btn-secondary" @click="open=false">Hủy</button><button class="btn btn-primary" :disabled="saving" @click="save">{{saving?'Đang lưu...':'Lưu menu'}}</button></template></BaseModal><ConfirmDialog :open="!!deleteId" title="Xóa menu" message="Menu con dùng ON DELETE CASCADE. Xóa một menu cha có thể xóa luôn toàn bộ menu con bên dưới." @cancel="deleteId=null" @confirm="remove"/></template>
