<script setup lang="ts">
import { onMounted, ref } from 'vue';import { Eye, RefreshCw } from 'lucide-vue-next';import { api } from '@/services/api';import { errorMessage } from '@/utils/errors';import { dateTime, money } from '@/utils/format';import type { Order } from '@/types/api';import PageHeader from '@/components/PageHeader.vue';import BaseModal from '@/components/BaseModal.vue';import PaginationBar from '@/components/PaginationBar.vue';import StatusBadge from '@/components/StatusBadge.vue';import EmptyState from '@/components/EmptyState.vue'
const rows=ref<Order[]>([]),page=ref(1),lastPage=ref(1),total=ref(0),status=ref(''),loading=ref(false),detail=ref<Order|null>(null),newStatus=ref(''),saving=ref(false),err=ref('');const statuses=['pending','confirmed','processing','shipping','completed','cancelled']
async function load(p=page.value){loading.value=true;try{const r=await api.orders({page:p,status:status.value||undefined});rows.value=r.data;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}finally{loading.value=false}}
async function show(id:number){err.value='';detail.value=await api.order(id);newStatus.value=detail.value.status}
async function update(){if(!detail.value)return;saving.value=true;err.value='';try{detail.value=await api.orderStatus(detail.value.order_id,newStatus.value);await show(detail.value.order_id);await load()}catch(e){err.value=errorMessage(e)}finally{saving.value=false}}
onMounted(()=>load())
</script>
<template><PageHeader title="Đơn hàng" description="Theo dõi và chuyển trạng thái đơn theo luồng nghiệp vụ được backend kiểm soát."><button class="btn btn-secondary" @click="load()"><RefreshCw :size="15"/>Làm mới</button></PageHeader><section class="card"><div class="toolbar"><div class="toolbar-group"><select v-model="status" class="select" @change="load(1)"><option value="">Tất cả trạng thái</option><option v-for="s in statuses" :value="s" :key="s">{{s}}</option></select></div><span class="muted" style="font-size:12px">{{total}} đơn hàng</span></div><div v-if="loading" class="loading-line"/><EmptyState v-if="!loading&&!rows.length" title="Chưa có đơn hàng"/><div v-else class="table-wrap"><table class="data-table"><thead><tr><th>Mã đơn</th><th>Khách hàng</th><th>Tổng tiền</th><th>Thanh toán</th><th>Trạng thái</th><th>Ngày tạo</th><th></th></tr></thead><tbody><tr v-for="x in rows" :key="x.order_id"><td><strong>#{{x.order_id}}</strong></td><td>User #{{x.user_id}}</td><td><strong>{{money(x.total_amount)}}</strong></td><td><StatusBadge v-if="x.payment" :value="x.payment.status"/><span v-else>—</span></td><td><StatusBadge :value="x.status"/></td><td>{{dateTime(x.created_at)}}</td><td><div class="actions"><button class="btn btn-secondary btn-sm" @click="show(x.order_id)"><Eye :size="14"/>Chi tiết</button></div></td></tr></tbody></table></div><PaginationBar v-if="rows.length" :page="page" :last-page="lastPage" :total="total" @change="load"/></section>
<BaseModal :open="!!detail" title="Chi tiết đơn hàng" wide @close="detail=null"><template v-if="detail"><div v-if="err" class="alert alert-danger">{{err}}</div><div class="detail-grid"><div class="detail-item"><span>Mã đơn</span><strong>#{{detail.order_id}}</strong></div><div class="detail-item"><span>Khách hàng</span><strong>User #{{detail.user_id}}</strong></div><div class="detail-item"><span>Tổng tiền</span><strong>{{money(detail.total_amount)}}</strong></div><div class="detail-item"><span>Thanh toán</span><strong>{{detail.payment?.method||'—'}} · {{detail.payment?.status||'—'}}</strong></div><div class="detail-item"><span>Người nhận</span><strong>{{detail.shipping_address?.receiver_name||'—'}} · {{detail.shipping_address?.receiver_phone||''}}</strong></div><div class="detail-item"><span>Địa chỉ giao hàng</span><strong>{{detail.shipping_address?.detailed_address}}, {{detail.shipping_address?.ward_commune}}, {{detail.shipping_address?.district}}, {{detail.shipping_address?.province_city}}</strong></div></div><div class="order-items"><h4>Sản phẩm trong đơn</h4><div class="table-wrap"><table class="data-table"><thead><tr><th>Sản phẩm</th><th>SL</th><th>Đơn giá đóng băng</th><th>Thành tiền</th></tr></thead><tbody><tr v-for="i in detail.items" :key="i.order_item_id"><td>{{i.product_name}}</td><td>{{i.quantity}}</td><td>{{money(i.price)}}</td><td>{{money(Number(i.price)*i.quantity)}}</td></tr></tbody></table></div></div><div style="margin-top:15px" class="form-grid"><label class="field"><span>Chuyển trạng thái</span><select v-model="newStatus"><option v-for="s in statuses" :key="s" :value="s">{{s}}</option></select><small>Backend sẽ từ chối chuyển trạng thái trái luật.</small></label><div class="field"><span>Ghi chú khách hàng</span><div class="detail-item"><strong>{{detail.note||'Không có ghi chú'}}</strong></div></div></div></template><template #footer><button class="btn btn-secondary" @click="detail=null">Đóng</button><button class="btn btn-primary" :disabled="saving||newStatus===detail?.status" @click="update">{{saving?'Đang cập nhật...':'Cập nhật trạng thái'}}</button></template></BaseModal></template>
