<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';import { Eye } from 'lucide-vue-next';import { api } from '@/services/api';import { errorMessage } from '@/utils/errors';import { dateTime, money } from '@/utils/format';import type { Payment } from '@/types/api';import PageHeader from '@/components/PageHeader.vue';import BaseModal from '@/components/BaseModal.vue';import PaginationBar from '@/components/PaginationBar.vue';import StatusBadge from '@/components/StatusBadge.vue';import EmptyState from '@/components/EmptyState.vue'
const rows=ref<Payment[]>([]),page=ref(1),lastPage=ref(1),total=ref(0),status=ref(''),detail=ref<Payment|null>(null),saving=ref(false),err=ref('');const form=reactive<any>({status:'pending',transaction_code:'',gateway_payload:''})
async function load(p=page.value){const r=await api.payments({page:p,status:status.value||undefined});rows.value=r.data;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}
async function show(id:number){detail.value=await api.payment(id);Object.assign(form,{status:detail.value.status,transaction_code:detail.value.transaction_code||'',gateway_payload:detail.value.gateway_payload?JSON.stringify(detail.value.gateway_payload,null,2):''});err.value=''}
async function save(){if(!detail.value)return;saving.value=true;err.value='';try{let payload=null;if(form.gateway_payload){try{payload=JSON.parse(form.gateway_payload)}catch{throw new Error('Gateway payload phải là JSON hợp lệ.')}}detail.value=await api.paymentStatus(detail.value.payment_id,{status:form.status,transaction_code:form.transaction_code||null,gateway_payload:payload});await load();detail.value=null}catch(e){err.value=errorMessage(e)}finally{saving.value=false}}
onMounted(()=>load())
</script>
<template><PageHeader title="Thanh toán" description="Đối soát trạng thái thanh toán 1-1 theo từng đơn hàng."/><section class="card"><div class="toolbar"><div class="toolbar-group"><select v-model="status" class="select" @change="load(1)"><option value="">Tất cả trạng thái</option><option value="pending">pending</option><option value="success">success</option><option value="failed">failed</option></select></div></div><EmptyState v-if="!rows.length" title="Chưa có dữ liệu thanh toán"/><div v-else class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Đơn hàng</th><th>Phương thức</th><th>Số tiền</th><th>Trạng thái</th><th>Mã giao dịch</th><th>Đã thanh toán</th><th></th></tr></thead><tbody><tr v-for="x in rows" :key="x.payment_id"><td>#{{x.payment_id}}</td><td>#{{x.order_id}}</td><td>{{x.method}}</td><td><strong>{{money(x.amount)}}</strong></td><td><StatusBadge :value="x.status"/></td><td>{{x.transaction_code||'—'}}</td><td>{{dateTime(x.paid_at)}}</td><td><div class="actions"><button class="btn btn-secondary btn-sm" @click="show(x.payment_id)"><Eye :size="14"/>Đối soát</button></div></td></tr></tbody></table></div><PaginationBar v-if="rows.length" :page="page" :last-page="lastPage" :total="total" @change="load"/></section><BaseModal :open="!!detail" title="Đối soát thanh toán" @close="detail=null"><div v-if="err" class="alert alert-danger">{{err}}</div><div class="form-grid"><label class="field"><span>Trạng thái</span><select v-model="form.status"><option value="pending">pending</option><option value="success">success</option><option value="failed">failed</option></select></label><label class="field"><span>Mã giao dịch</span><input v-model="form.transaction_code"/></label><label class="field full"><span>Gateway payload (JSON)</span><textarea v-model="form.gateway_payload" rows="8"/></label></div><template #footer><button class="btn btn-secondary" @click="detail=null">Hủy</button><button class="btn btn-primary" :disabled="saving" @click="save">{{saving?'Đang lưu...':'Cập nhật thanh toán'}}</button></template></BaseModal></template>
