<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Plus, Pencil, Trash2, Search, Upload, PackageOpen } from 'lucide-vue-next'
import { api } from '@/services/api';import { errorMessage } from '@/utils/errors';import { money, slugify } from '@/utils/format'
import type { Category, Product } from '@/types/api'
import PageHeader from '@/components/PageHeader.vue';import BaseModal from '@/components/BaseModal.vue';import PaginationBar from '@/components/PaginationBar.vue';import StatusBadge from '@/components/StatusBadge.vue';import ConfirmDialog from '@/components/ConfirmDialog.vue';import EmptyState from '@/components/EmptyState.vue'
const rows=ref<Product[]>([]),categories=ref<Category[]>([]),page=ref(1),lastPage=ref(1),total=ref(0),q=ref(''),loading=ref(false),open=ref(false),saving=ref(false),err=ref(''),editing=ref<Product|null>(null),deleteId=ref<number|null>(null),imageFile=ref<File|null>(null)
const form=reactive<any>({category_id:null,media_id:null,name:'',slug:'',sku:'',short_description:'',description:'',price:0,stock_quantity:0,is_active:true})
async function load(p=page.value){loading.value=true;try{const r=await api.products({page:p,q:q.value||undefined});rows.value=r.data;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}finally{loading.value=false}}
async function loadCategories(){categories.value=(await api.categories()).data}
function create(){editing.value=null;imageFile.value=null;Object.assign(form,{category_id:categories.value[0]?.category_id||null,media_id:null,name:'',slug:'',sku:'',short_description:'',description:'',price:0,stock_quantity:0,is_active:true});err.value='';open.value=true}
function edit(x:Product){editing.value=x;imageFile.value=null;Object.assign(form,{category_id:x.category_id,media_id:x.media_id||null,name:x.name,slug:x.slug,sku:x.sku,short_description:x.short_description||'',description:x.description||'',price:Number(x.price),stock_quantity:x.stock_quantity,is_active:x.is_active});err.value='';open.value=true}
function autoSlug(){if(!editing.value||!form.slug)form.slug=slugify(form.name)}
function pickImage(e:Event){imageFile.value=(e.target as HTMLInputElement).files?.[0]||null}
async function save(){saving.value=true;err.value='';try{const saved=await api.saveProduct({...form,category_id:Number(form.category_id),price:Number(form.price),stock_quantity:Number(form.stock_quantity)},editing.value?.product_id);if(imageFile.value)await api.uploadProductImage(saved.product_id,imageFile.value);open.value=false;await load()}catch(e){err.value=errorMessage(e)}finally{saving.value=false}}
async function remove(){if(!deleteId.value)return;try{await api.deleteProduct(deleteId.value);deleteId.value=null;await load()}catch(e){alert(errorMessage(e))}}
onMounted(async()=>{await Promise.all([load(),loadCategories()])})
</script>
<template><PageHeader title="Sản phẩm" description="Quản lý thông tin bán hàng, tồn kho, giá và ảnh sản phẩm."><button class="btn btn-primary" @click="create"><Plus :size="16"/>Thêm sản phẩm</button></PageHeader>
<section class="card"><div class="toolbar"><div class="toolbar-group"><div class="search-box"><Search :size="16"/><input v-model="q" placeholder="Tìm theo tên sản phẩm..." @keyup.enter="load(1)"/></div><button class="btn btn-secondary" @click="load(1)">Tìm kiếm</button></div><span class="muted" style="font-size:12px">{{total}} sản phẩm</span></div><div v-if="loading" class="loading-line"/><EmptyState v-if="!loading&&!rows.length" title="Chưa có sản phẩm"><button class="btn btn-primary btn-sm" @click="create"><Plus :size="14"/>Tạo sản phẩm đầu tiên</button></EmptyState><div v-else class="table-wrap"><table class="data-table"><thead><tr><th>Sản phẩm</th><th>SKU</th><th>Danh mục</th><th>Giá</th><th>Tồn kho</th><th>Trạng thái</th><th></th></tr></thead><tbody><tr v-for="x in rows" :key="x.product_id"><td><div class="cell-title"><img v-if="x.media?.drive_view_url" :src="x.media.drive_view_url"/><div v-else style="width:42px;height:42px;border:1px solid var(--line);border-radius:9px;display:grid;place-items:center"><PackageOpen :size="18"/></div><div><strong>{{x.name}}</strong><small>#{{x.product_id}} · {{x.slug}}</small></div></div></td><td>{{x.sku}}</td><td>{{x.category?.name||x.category_id}}</td><td><strong>{{money(x.price)}}</strong></td><td><span :class="x.stock_quantity<=5?'badge badge-danger':''">{{x.stock_quantity}}</span></td><td><StatusBadge :value="x.is_active"/></td><td><div class="actions"><button class="btn btn-secondary btn-sm" @click="edit(x)"><Pencil :size="14"/>Sửa</button><button class="btn btn-danger btn-sm" @click="deleteId=x.product_id"><Trash2 :size="14"/></button></div></td></tr></tbody></table></div><PaginationBar v-if="rows.length" :page="page" :last-page="lastPage" :total="total" @change="load"/></section>
<BaseModal :open="open" :title="editing?'Sửa sản phẩm':'Thêm sản phẩm'" wide @close="open=false"><div v-if="err" class="alert alert-danger">{{err}}</div><div class="form-grid"><label class="field"><span>Tên sản phẩm *</span><input v-model="form.name" @blur="autoSlug"/></label><label class="field"><span>Slug *</span><input v-model="form.slug"/></label><label class="field"><span>SKU *</span><input v-model="form.sku"/></label><label class="field"><span>Danh mục *</span><select v-model.number="form.category_id"><option v-for="c in categories" :key="c.category_id" :value="c.category_id">{{c.name}}</option></select></label><label class="field"><span>Giá bán</span><input v-model.number="form.price" type="number" min="0" step="1000"/></label><label class="field"><span>Tồn kho</span><input v-model.number="form.stock_quantity" type="number" min="0"/></label><label class="field full"><span>Mô tả ngắn</span><textarea v-model="form.short_description" rows="3"/></label><label class="field full"><span>Mô tả chi tiết</span><textarea v-model="form.description" rows="7"/></label><label class="field full"><span>Ảnh sản phẩm</span><input type="file" accept="image/*" @change="pickImage"/><small><Upload :size="12" style="vertical-align:-2px"/> {{imageFile?.name||'Chọn ảnh mới nếu muốn thay ảnh hiện tại. Ảnh được upload qua Google Drive.'}}</small></label><div class="switch-row full"><span>Cho phép hiển thị/bán sản phẩm</span><label class="switch"><input v-model="form.is_active" type="checkbox"><i/></label></div></div><template #footer><button class="btn btn-secondary" @click="open=false">Hủy</button><button class="btn btn-primary" :disabled="saving" @click="save">{{saving?'Đang lưu...':'Lưu sản phẩm'}}</button></template></BaseModal>
<ConfirmDialog :open="!!deleteId" title="Xóa sản phẩm" message="Không thể xóa sản phẩm đã tồn tại trong lịch sử đơn hàng. Nếu chỉ muốn ngừng bán, hãy chuyển trạng thái sản phẩm sang tắt." @cancel="deleteId=null" @confirm="remove"/></template>
