<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';import { Eye, Search } from 'lucide-vue-next';import { api } from '@/services/api';import { errorMessage } from '@/utils/errors';import { dateTime } from '@/utils/format';import type { User } from '@/types/api';import PageHeader from '@/components/PageHeader.vue';import BaseModal from '@/components/BaseModal.vue';import PaginationBar from '@/components/PaginationBar.vue';import StatusBadge from '@/components/StatusBadge.vue';import EmptyState from '@/components/EmptyState.vue'
const rows=ref<User[]>([]),page=ref(1),lastPage=ref(1),total=ref(0),q=ref(''),detail=ref<User|null>(null),saving=ref(false),err=ref('');const form=reactive({is_active:true,is_marketing_allowed:false})
async function load(p=page.value){const r=await api.users({page:p,q:q.value||undefined});rows.value=r.data;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}
async function show(id:number){detail.value=await api.user(id);form.is_active=detail.value.is_active;form.is_marketing_allowed=detail.value.is_marketing_allowed;err.value=''}
async function save(){if(!detail.value)return;saving.value=true;err.value='';try{detail.value=await api.updateUser(detail.value.user_id,{...form});await load()}catch(e){err.value=errorMessage(e)}finally{saving.value=false}}
onMounted(()=>load())
</script>
<template><PageHeader title="Khách hàng" description="Tra cứu tài khoản, địa chỉ, social login và quyền nhận marketing."/><section class="card"><div class="toolbar"><div class="toolbar-group"><div class="search-box"><Search :size="16"/><input v-model="q" placeholder="Email, tên hoặc số điện thoại..." @keyup.enter="load(1)"/></div><button class="btn btn-secondary" @click="load(1)">Tìm kiếm</button></div></div><EmptyState v-if="!rows.length" title="Chưa có khách hàng"/><div v-else class="table-wrap"><table class="data-table"><thead><tr><th>Khách hàng</th><th>Điện thoại</th><th>Vai trò</th><th>Marketing</th><th>Trạng thái</th><th>Ngày tạo</th><th></th></tr></thead><tbody><tr v-for="x in rows" :key="x.user_id"><td><div class="cell-title"><img v-if="x.avatar?.drive_view_url" :src="x.avatar.drive_view_url"/><div><strong>{{x.full_name}}</strong><small>#{{x.user_id}} · {{x.email}}</small></div></div></td><td>{{x.phone||'—'}}</td><td><StatusBadge :value="x.role"/></td><td>{{x.is_marketing_allowed?'Đồng ý':'Không'}}</td><td><StatusBadge :value="x.is_active"/></td><td>{{dateTime(x.created_at)}}</td><td><div class="actions"><button class="btn btn-secondary btn-sm" @click="show(x.user_id)"><Eye :size="14"/>Chi tiết</button></div></td></tr></tbody></table></div><PaginationBar v-if="rows.length" :page="page" :last-page="lastPage" :total="total" @change="load"/></section>
<BaseModal :open="!!detail" title="Chi tiết khách hàng" wide @close="detail=null"><template v-if="detail"><div v-if="err" class="alert alert-danger">{{err}}</div><div class="detail-grid"><div class="detail-item"><span>Họ tên</span><strong>{{detail.full_name}}</strong></div><div class="detail-item"><span>Email</span><strong>{{detail.email}}</strong></div><div class="detail-item"><span>Điện thoại</span><strong>{{detail.phone||'—'}}</strong></div><div class="detail-item"><span>Vai trò</span><strong>{{detail.role}}</strong></div></div><h4 style="font-size:12px;margin:16px 0 8px">Quyền tài khoản</h4><div class="form-grid"><div class="switch-row"><span>Tài khoản hoạt động</span><label class="switch"><input v-model="form.is_active" type="checkbox"><i/></label></div><div class="switch-row"><span>Cho phép marketing</span><label class="switch"><input v-model="form.is_marketing_allowed" type="checkbox"><i/></label></div></div><h4 style="font-size:12px;margin:16px 0 8px">Địa chỉ</h4><div v-if="detail.addresses?.length" class="section-list"><div class="detail-item" v-for="a in detail.addresses" :key="a.address_id"><span>{{a.is_default?'Mặc định':'Địa chỉ'}} · {{a.receiver_name}} · {{a.receiver_phone}}</span><strong>{{a.detailed_address}}, {{a.ward_commune}}, {{a.district}}, {{a.province_city}}</strong></div></div><p v-else class="muted" style="font-size:12px">Chưa có địa chỉ.</p><h4 style="font-size:12px;margin:16px 0 8px">Tài khoản mạng xã hội</h4><div v-if="detail.social_accounts?.length" class="section-list"><div class="detail-item" v-for="s in detail.social_accounts" :key="s.social_account_id"><span>{{s.provider}}</span><strong>{{s.provider_user_id}}</strong></div></div><p v-else class="muted" style="font-size:12px">Không liên kết Google/Facebook.</p></template><template #footer><button class="btn btn-secondary" @click="detail=null">Đóng</button><button class="btn btn-primary" :disabled="saving" @click="save">{{saving?'Đang lưu...':'Lưu quyền tài khoản'}}</button></template></BaseModal></template>
